# run: conda env create --file requirements.yaml
name: rto_nime22
dependencies:

- python=3.7
- pip
- click
- pandas
- matplotlib
- seaborn
- ipywidgets
- scikit-learn

- conda-forge::opentsne
- conda-forge::tslearn

- pip: 
  - dash
  - dash-daq
  - dash-bootstrap-components
